### ISSUE TITLE
Crash w/OpenGL 2.1 AMD/Linux driver without the GL_ARB_vertex_buffer_object extension available

### ISSUE THREAD

**Issue by jiyunomegami** [raduprv/Eternal-Lands#25]
I will describe how I got el to work with the fairly new AMD radeon crimson 15.302 driver for Linux.
The problems described here may be of interest if there are problems with other new drivers as well.
I have since downgraded to an older "catalyst" driver, which does not have any of these problems.

relevant section from glxinfo:

```
OpenGL vendor string: ATI Technologies Inc.
OpenGL renderer string: AMD Radeon R9 200 / HD 7900 Series
OpenGL version string: 1.4 (2.1 (4.5.13416 Compatibility Profile Context 15.302))
OpenGL extensions:
    GL_ARB_depth_texture, GL_ARB_draw_buffers, GL_ARB_fragment_program, 
    GL_ARB_fragment_program_shadow, GL_ARB_framebuffer_object, GL_ARB_imaging, 
    GL_ARB_multisample, GL_ARB_multitexture, GL_ARB_occlusion_query, 
    GL_ARB_point_parameters, GL_ARB_point_sprite, GL_ARB_shadow, 
    GL_ARB_shadow_ambient, GL_ARB_texture_border_clamp, 
    GL_ARB_texture_compression, GL_ARB_texture_cube_map, 
    GL_ARB_texture_env_add, GL_ARB_texture_env_combine, 
    GL_ARB_texture_env_crossbar, GL_ARB_texture_env_dot3, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_non_power_of_two, 
    GL_ARB_texture_rectangle, GL_ARB_transpose_matrix, GL_ARB_vertex_program, 
    GL_ARB_window_pos, GL_ATIX_texture_env_combine3, GL_ATI_draw_buffers, 
    GL_ATI_texture_env_combine3, GL_ATI_texture_mirror_once, GL_EXT_abgr, 
    GL_EXT_bgra, GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_copy_texture, GL_EXT_draw_range_elements, GL_EXT_fog_coord, 
    GL_EXT_framebuffer_blit, GL_EXT_framebuffer_multisample, 
    GL_EXT_framebuffer_object, GL_EXT_multi_draw_arrays, GL_EXT_packed_pixels, 
    GL_EXT_point_parameters, GL_EXT_rescale_normal, GL_EXT_secondary_color, 
    GL_EXT_separate_specular_color, GL_EXT_shadow_funcs, GL_EXT_stencil_wrap, 
    GL_EXT_subtexture, GL_EXT_texture3D, GL_EXT_texture_compression_s3tc, 
    GL_EXT_texture_edge_clamp, GL_EXT_texture_env_add, 
    GL_EXT_texture_env_combine, GL_EXT_texture_env_dot3, GL_EXT_texture_lod, 
    GL_EXT_texture_lod_bias, GL_EXT_texture_mirror_clamp, 
    GL_EXT_texture_object, GL_EXT_texture_rectangle, GL_EXT_vertex_array, 
    GL_IBM_texture_mirrored_repeat, GL_INGR_blend_func_separate, 
    GL_NV_texture_rectangle, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_border_clamp, GL_SGIS_texture_edge_clamp, 
    GL_SGIS_texture_lod, GL_SGIX_shadow_ambient, GL_SUN_multi_draw_arrays
```

Since el seems to require VBO, I made it use the non-ARB procedures when the extension is not available.
Like this:

```
diff --git a/load_gl_extensions.c b/load_gl_extensions.c
index 20efa84..ac32883 100644
--- a/load_gl_extensions.c
+++ b/load_gl_extensions.c
@@ -892,6 +892,26 @@ static GLboolean el_init_GL_ARB_vertex_buffer_object()
        return r;
 }

+/* VBO is a core part of OpenGL versions >= 1.5 */
+static GLboolean el_init_GL_CORE_vertex_buffer_object()
+{
+       GLboolean r = GL_TRUE;
+
+       r = ((ELglBindBufferARB = (PFNGLBINDBUFFERARBPROC)SDL_GL_GetProcAddress("glBindBuffer")) != NULL) && r;
+       r = ((ELglBufferDataARB = (PFNGLBUFFERDATAARBPROC)SDL_GL_GetProcAddress("glBufferData")) != NULL) && r;
+       r = ((ELglBufferSubDataARB = (PFNGLBUFFERSUBDATAARBPROC)SDL_GL_GetProcAddress("glBufferSubData")) != NULL) && r;
+       r = ((ELglDeleteBuffersARB = (PFNGLDELETEBUFFERSARBPROC)SDL_GL_GetProcAddress("glDeleteBuffers")) != NULL) && r;
+       r = ((ELglGenBuffersARB = (PFNGLGENBUFFERSARBPROC)SDL_GL_GetProcAddress("glGenBuffers")) != NULL) && r;
+       r = ((ELglGetBufferParameterivARB = (PFNGLGETBUFFERPARAMETERIVARBPROC)SDL_GL_GetProcAddress("glGetBufferParameteriv")) != NULL) && r;
+       r = ((ELglGetBufferPointervARB = (PFNGLGETBUFFERPOINTERVARBPROC)SDL_GL_GetProcAddress("glGetBufferPointerv")) != NULL) && r;
+       r = ((ELglGetBufferSubDataARB = (PFNGLGETBUFFERSUBDATAARBPROC)SDL_GL_GetProcAddress("glGetBufferSubData")) != NULL) && r;
+       r = ((ELglIsBufferARB = (PFNGLISBUFFERARBPROC)SDL_GL_GetProcAddress("glIsBuffer")) != NULL) && r;
+       r = ((ELglMapBufferARB = (PFNGLMAPBUFFERARBPROC)SDL_GL_GetProcAddress("glMapBuffer")) != NULL) && r;
+       r = ((ELglUnmapBufferARB = (PFNGLUNMAPBUFFERARBPROC)SDL_GL_GetProcAddress("glUnmapBuffer")) != NULL) && r;
+
+       return r;
+}
+
 static GLboolean el_init_GL_ARB_occlusion_query()
 {
        GLboolean r = GL_TRUE;
@@ -1198,6 +1218,12 @@ void init_opengl_extensions()
                {
                        extensions |= 1 << arb_vertex_buffer_object;
                }
+       } else {
+               e = el_init_GL_CORE_vertex_buffer_object();
+               if (e == GL_TRUE)
+               {
+                       extensions |= 1 << arb_vertex_buffer_object;
+               }
        }
 /*     GL_ARB_vertex_buffer_object             */
 /*     GL_ARB_shadow                           */
```

Without the above patch el crashes when attempting to call ELglGenBuffersARB (which is NULL)
For example, when creating a new character:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000065761b in eternal_lands::HardwareBuffer::HardwareBuffer (
    this=0x1ea5ea0) at engine/hardwarebuffer.cpp:16
#2  0x0000000000603728 in ec::Effect::Effect (this=0x1ea5e20)
    at eye_candy/eye_candy.h:2034
#3  0x0000000000605860 in ec::CampfireEffect::CampfireEffect (this=0x1ea5e20, 
    _base=0xadbec0 <eye_candy>, _dead=0x1ea5e00, _pos=0x1ea5d88, 
    _obstructions=0xadc0c0 <fire_obstructions_list>, _hue_adjust=0, 
    _saturation_adjust=1, _scale=1.5, _LOD=10)
    at eye_candy/effect_campfire.cpp:209
#4  0x00000000005cf104 in ec_create_campfire (x=26.9383049, y=79.5691757, z=0, 
    hue_adjust=0, saturation_adjust=1, LOD=10, scale=1.5)
    at eye_candy_wrapper.cpp:1433
#5  0x00000000004dcfc8 in real_add_particle_sys (
    file_name=0x7fffffffdba0 "./particles/fire_big.part", x_pos=26.9383049, 
    y_pos=79.5691757, z_pos=0, dynamic=0) at particles.c:780
#6  0x00000000004dcaaf in add_map_particle_sys (
    file_name=0x7fffffffdba0 "./particles/fire_big.part", x_pos=26.9383049, 
    y_pos=79.5691757, z_pos=0, dynamic=0) at particles.c:718
#7  0x0000000000498b8e in do_load_map (
    file_name=0x6ab13c "./maps/newcharactermap.elm", 
    update_function=0x4b860b <updat_func>) at io/map_io.c:599
...
```

This happens even if vertex buffer is disabled in settings.
Even with the above patch, if vertex buffer is enabled, el crashes in draw_water_background.

I did the same thing for ARB_vertex_shader and ARB_shader_objects,
and forced arb_fragment_shader and arb_shading_language_100 to be supported as they should be.
Unfortunately the shaders would not compile.

I was able to create a new character with the above patch, but
ran into some problems with the eye candy.
I didn't see any obvious reasons for the crashes or null buffer, so I just disabled the relevant code.

```
diff --git a/eye_candy/effect_selfmagic.cpp b/eye_candy/effect_selfmagic.cpp
index a0698ac..02db324 100644
--- a/eye_candy/effect_selfmagic.cpp
+++ b/eye_candy/effect_selfmagic.cpp
@@ -778,6 +778,8 @@ namespace ec
        void SelfMagicEffect::draw(const Uint64 usec)
        {
 #ifdef NEW_TEXTURES
+               // crash after getting off boat?
+               //return;
                if (capless_cylinders != 0)
                {
                        capless_cylinders->draw(alpha_scale);
diff --git a/eye_candy/effect_teleporter.cpp b/eye_candy/effect_teleporter.cpp
index adfaf7e..f65b2d6 100644
--- a/eye_candy/effect_teleporter.cpp
+++ b/eye_candy/effect_teleporter.cpp
@@ -196,6 +196,8 @@ namespace ec
        void TeleporterEffect::draw(const Uint64 usec)
        {
 #ifdef NEW_TEXTURES
+               // crashed...
+               //return;
                capless_cylinders->draw(1.0f);
 #else  /* NEW_TEXTURES */
                for (std::vector<Shape*>::iterator iter = capless_cylinders.begin(); iter
diff --git a/eye_candy/eye_candy.cpp b/eye_candy/eye_candy.cpp
index 563c3f4..f40d2e6 100644
--- a/eye_candy/eye_candy.cpp
+++ b/eye_candy/eye_candy.cpp
@@ -218,6 +218,7 @@ namespace ec
                corner[2] = Vec3(pos + base->corner_offset1 * size);
                corner[3] = Vec3(pos - base->corner_offset2 * size);

+               if (buffer == NULL) return;
                for (i = 0; i < 4; i++)
                {
                        index = particle_count * 4 + i;
@@ -928,6 +929,7 @@ namespace ec

                vertex_buffer.bind(el::hbt_vertex);
                vertices = static_cast<CaplessCylindersVertex*>(vertex_buffer.map(el::hbt_vertex, el::hbat_write_only));
+                if (vertices == NULL) return; // crash entering boat on Isla Prima (vertices was null)

                size = 3 * sizeof(GLushort) * facet_count;
```

I was able to create a new character, and complete the newbie tutorial with the above patches.
No shadows or reflections. The ocean and puddles were just one solid color with a slight gradient.

Now I am using the older catalyst drivers (version 15.201.1151) that supports all the extensions.
No problems whatsoever.

**Comment by pjbroad** [comment]
This was long ago, I presume it was a temporary driver issue so will close.
